# Generated by Django 5.2.8 on 2025-12-23 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_rank_level', models.IntegerField(blank=True, null=True)),
                ('view_min_rank_level', models.IntegerField(blank=True, null=True, verbose_name='관리 가능 최소 직급 레벨(이상)')),
                ('require_approval', models.BooleanField(default=False)),
                ('allowed_departments', models.ManyToManyField(blank=True, related_name='facilities_allowed', to='accounts.department', verbose_name='예약 가능 부서(선택)')),
                ('allowed_ranks', models.ManyToManyField(blank=True, related_name='facilities_allowed', to='accounts.rank', verbose_name='예약 가능 직급(선택)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '반려'), ('CANCELED', '취소')], default='APPROVED', max_length=20)),
                ('decision_note', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservation.facility')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['facility', 'date', 'start_time', 'end_time'], name='reservation_facilit_ed92d6_idx')],
            },
        ),
    ]
