"""
Django settings for CB project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # [추가] 환경변수 로드

# 1. Base Directory 설정
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. .env 파일 로드 (이 코드가 if문보다 위에 있어야 함)
load_dotenv(BASE_DIR / '.env', override=True)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mo)pqf9f%$p$&(7k+@34%7$^gu_^k0r@a312j3m3cgkg*su(!@'

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'community',
    'messenger',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UpdateLastActivityMiddleware',

]

ROOT_URLCONF = 'CB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'messenger.context_processors.unread_count',
                'accounts.context_processors.online_users',
            ],
        },
    },
]

WSGI_APPLICATION = 'CB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DEV') == 'True':
    # [로컬 개발 환경]
    print("📢 현재 모드: 로컬 개발 (SQLite)")
    DEBUG = True
    ALLOWED_HOSTS = ['*'] # 개발할 땐 편하게
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # [AWS 서버 환경]
    print("🚀 현재 모드: AWS 배포 (MySQL/RDS)")
    DEBUG = False
    # 서버 IP나 도메인을 꼭 넣어야 함 (보안 에러 방지)
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '여기에_EC2_퍼블릭IP'] 

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            # .env에서 실제 값을 가져오도록 수정했습니다
            'NAME': os.environ.get('DB_NAME'),     
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
ALLOWED_HOSTS = ['*']

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key')
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'

# 로그인 성공 시 이동할 URL (게시판 목록)
LOGIN_REDIRECT_URL = '/community/'

# 로그아웃 시 이동할 URL (로그인 페이지)
LOGOUT_REDIRECT_URL = '/accounts/login/'

# 1. 개발할 때 쓰는 정적 파일 위치
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 2. 배포할 때 모이는 위치 (Nginx가 바라볼 곳)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# 3. 미디어 파일 (유저 업로드) 설정
# URL은 웹에서 접근하는 주소
MEDIA_URL = '/media/'

# ROOT는 실제 파일이 저장되는 서버 경로
MEDIA_ROOT = BASE_DIR / 'media'


SUMMERNOTE_THEME = 'bs5'  # 부트스트랩 5 테마 사용

SUMMERNOTE_CONFIG = {
    # 에디터 크기 설정
    'width': '100%',
    'height': '400',
    'lang': 'ko-KR',  # 한국어 설정
    
    # 툴바 설정 (필요한 것만 남김)
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'underline', 'clear']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']], # picture가 사진 넣는 버튼입니다.
        ['view', ['fullscreen', 'codeview', 'help']],
    ],
    # 이미지 업로드 시 서버에 파일로 저장하도록 설정
    'attachment_require_authentication': True, # 로그인한 사람만 파일 업로드 가능
    'disable_attachment': False,
}